### ISSUE TITLE
OWC support

### ISSUE THREAD

**Issue by izabala123** [YingyiLiu/HAMS#10]
Hi Yingyi

I've seen the Moonpool example, it's very interesting. 
Does it mean that HAMS supports Oscillating Water Columns?
(that would be good news :-) )

Best regards
Iñaki

**Comment by YingyiLiu** [comment]
Dear Iñaki,

Thanks for the message.
The moonpool example does not include any viscosity. It is still within the
framework of the pure potential flow theory.
OWC has an internal free surface over which the pressure is changed from
outside the chamber. To model an OWC, the BEM needs to be modified, this
feature is not yet available in HAMS.
I will inform you when this functionality is ready to use (but may not be
in the recent future).

Best regards,
Yingyi


Iñaki Zabala ***@***.***> 于2021年5月21日周五 下午4:46写道：

**Comment by izabala123** [comment]
Thank you Yingyi. I look forward to hearing from you.
