### ISSUE TITLE
Support zero and infinite frequency response

### ISSUE THREAD

**Issue by gbarter** [YingyiLiu/HAMS#16]
Hi Yingyi,

Does HAMS support the 0-frequency and infinite-frequency response?  Maybe the infinite frequency through some Wamit-style use of negative frequency input values?

Many thanks,
Garrett

**Comment by YingyiLiu** [comment]
Dear Garrett,

Yes, HAMS can support the 0- and infinite-frequencies calculation (the part
being commented out in the main program). I need to have some time to
enable that.
The functionality is not realized via infinite frequency input, but by
modifying the Green function for the two special cases. I will let you know
when this functionality is ready to use.

Best regards,
Yingyi

Garrett Barter ***@***.***> 于2021年7月1日周四 上午3:49写道：

**Comment by gbarter** [comment]
Thank you for the quick response.  Let me know when you get around to making these changes.  In the meantime, we will use a very large finite frequency to approximate the infinite frequency response.

**Comment by gbarter** [comment]
I see in the commented out section in HAMS_Prog running very [small](https://github.com/YingyiLiu/HAMS/blob/master/SourceCode/HAMS_Prog.f90#L221) and [negative](https://github.com/YingyiLiu/HAMS/blob/master/SourceCode/HAMS_Prog.f90#L247) frequency values.  If it helps, HAMS does seem to run fine and give reasonable answers if given a frequency of 0.0.

**Comment by YingyiLiu** [comment]
Dear Garrett,

I have enabled the functionality for the two frequency limits in the latest
updates. I removed the commented-out section and coded this part in a much
simpler way.
Please note that for the time being, the functionality works exactly
correctly for the infinite-depth case, while for the finite-depth case
(especially when the water depth is very shallow in comparison to the
draught of the floating body), this functionality should be used as an
approximation for the exact value (typically having a relative error up to
20~30%). I will study the precise way of evaluating the limits in
finite-depth conditions. I will let you know when this improvement is ready.

Best regards,
Yingyi

Garrett Barter ***@***.***> 于2021年7月1日周四 下午8:50写道：

**Comment by gbarter** [comment]
Things are working great- thank you!

Might want to update the documentation regarding the new line in the Control file, but this Issue has definitely been addressed.

**Comment by YingyiLiu** [comment]
Thanks, the documentation has been updated.

Garrett Barter ***@***.***> 于2021年7月3日周六 上午1:14写道：
