### ISSUE TITLE
Q about enhanced endo's method

### ISSUE THREAD

**Issue by IL-1** [YingyiLiu/HAMS#17]
Dear Dr. Liu,

Thanks for sharing your invaluable asset.
As I read your paper, titled enhanced Endo's method, it was very interesting and informative. I appreciate it again. I was just wondering if this HAMS code has been updated following that article.

Thanks in advance for your answer.
Regards,
Ikjae

**Comment by YingyiLiu** [comment]
Dear Ikjae,

Thank you for your inquiry. I just see your message. 
Actually, not yet, but I can send you via email the HAMS executable program compiled with Endo's method.

Regards, 
Yingyi

**Comment by IkjaeLee** [comment]
Thanks for the response. I'd really appreciate it if you do that!! My email address is ick7140@gmail.com
For now I have steady forward speed (Neumann-Kelvin) and zero speed deep water HOBEM codes, which I have written in MATLAB but will be translated to FORTRAN in the near future. I would like to contribute it to HAMS at some time later.
Thanks again!!
Ikjae
