### ISSUE TITLE
Function on multiple bodies and 2nd-order wave forces

### ISSUE THREAD

**Issue by YiqXia** [YingyiLiu/HAMS#19]
Dear Dr. Liu,

Thank you so much for sharing your invaluable asset.
Now our team is working on a floater with 2 bodies. We are wondering whether HAMS can work on multiple bodies and whether it can calculate 2nd-order wave force. If not, is there any future plan to include these functions?

Thanks in advance for your answer.
Regards,
XIA

**Comment by YingyiLiu** [comment]
Dear Xia,

Thanks for your comment. Unfortunately, at the present stage, I do not have time and resource to work on the two functionalities as you mentioned. Indeed, I am not really sure at the moment when I will start the work. I must settle down first. Thank you for your interest.

Regards,
Yingyi
