### ISSUE TITLE
Mesh conversion

### ISSUE THREAD

**Issue by Aiswariak** [YingyiLiu/HAMS#20]
Hello,
I am new to this software and was trying to find the motion RAO of a floating structure. I have modeled a cylinder in Rhino and was trying to do the mesh conversion using 'RunWAMIT_MeshTran.bat', but after running that I am getting many files that are of 0B. So all the files are empty. 
How Can I proceed further? I am unable to find out where I am making the mistake. 
I am attaching the associated folder here 
[Trial.zip](https://github.com/YingyiLiu/HAMS/files/9299426/Trial.zip)

Thank you

**Comment by YingyiLiu** [comment]
The control file Settings.ctrl should not be deleted or empty, otherwise you will get 0B output files.
