### ISSUE TITLE
Inputs to the subroutines in modules AssbMatx_irr

### ISSUE THREAD

**Issue by austinerees** [YingyiLiu/HAMS#27]
Greetings of the day to you Dr.Yingy. I was studying the HAMS program and it is a great tool for learning as it is. However, I  would like to kindly know what inputs were feed into the subroutines of the AssbMatx_irr modules .
Kind regards
Rees

**Comment by YingyiLiu** [comment]
You can find the inputs at the beginning of the subroutine. The interface defines the inputs.

**Comment by austinerees** [comment]
Thank you very much for your response. Like I mentioned earlier in that
module, there is for instance a subroutine ASSB_LEFT with inputs
AMAT,IPIV,NELEM and NSYS .what are these inputs for? subroutines?maybe a
little bit of commenting would be helpful for others as well.

Kind regards
Rees

**Comment by YingyiLiu** [comment]
Thank you for your question. But this is a long story to tell, and to be honest currently I do not have the resources and time to answer these questions alike. Thanks.

**Comment by austinerees** [comment]
Thank you Dr. Yingyi. I honestly didn't mean to bore you out with my
questions.i didn't read my last comment before sending them.i wanted to
know what inputs they are not what they do.In other words what parameters
are been feed into that subroutines as I find your tool very helpful for
studying wave structure interactions and going through those referenced
papers,they make sense to me but I got stocked over there.

Thank you

**Comment by mancellin** [comment]
@austinerees
From my limited understanding of HAMS, in the file `AssbMatx.f90`:
- `NSYS` is the number of linear systems to be solved (the number of different sea states to be studied, I guess)
- `NELEM` is the number of panels in the mesh
- `AMAT` is used to store the matrices of the linear systems, and then the LU decomposition of these matrices using [lapack](https://netlib.org/lapack/explore-html/d3/d01/group__complex16_g_ecomputational_ga5b625680e6251feb29e386193914981c.html)
- `IPIV` is an additional information about the LU decomposition of each matrix.
- `BRMAT` and `BDMAT` are the right-hand side of the linear systems, respectively for radiation and diffraction problems.
- `MXPOT` is the potential on the body hull, that is the solution of the linear systems.

In `AssbMatrx_irr.f90` there is some additional complexity to remove irregular frequencies and I'm less familiar with that.

**Comment by austinerees** [comment]
Thank you so very much for this clarification mat!
I'm super grateful
