### ISSUE TITLE
issue about control file

### ISSUE THREAD

**Issue by Dylan0824** [YingyiLiu/HAMS#28]
Hi,
I use this program recently to do my work, and i have 2 questions about the control file.
The first is that whats the meaning of the '2.D0', i see the control file in test case, and i found that like the numer of the water depth, it writes '2.D0', whats the meaing of the D?
The second is that whats the meaning of 2 options 'Reference_body_length' and 'Wave_diffrac_solution', and i dont see any info in the manual,
Thank you very much for the help.

**Comment by Dylan0824** [comment]
Hi, 
i also want to know how can i get the free surface elevation and pressure data because the out file seems dont include the free surface.

**Comment by mancellin** [comment]
>  The first is that whats the meaning of the '2.D0', i see the control file in test case, and i found that like the numer of the water depth, it writes '2.D0', whats the meaing of the D?

I think I can easily answer this one: this is Fortran's scientific notation for double precision number. You can think of it as equivalent to the more common "E notation" `2.e0`.

**Comment by YingyiLiu** [comment]
> Hi, i also want to know how can i get the free surface elevation and pressure data because the out file seems dont include the free surface.

Free surface elevation and the hydrodynamic pressure are equivalent in nondimensional value at the free surface.

**Comment by Dylan0824** [comment]
> I think I can easily answer this one: this is Fortran's scientific notation for double precision number. You can think of it as equivalent to the more common "E notation" `2.e0`.
> Free surface elevation and the hydrodynamic pressure are equivalent in nondimensional value at the free surface.

Thank you for the help. It helps me a lot.
THank you again!

**Comment by Dylan0824** [comment]
> I think I can easily answer this one: this is Fortran's scientific notation for double precision number. You can think of it as equivalent to the more common "E notation" `2.e0`.
> Free surface elevation and the hydrodynamic pressure are equivalent in nondimensional value at the free surface.

Thank you for the help. It helps me a lot.
THank you again!

**Comment by Dylan0824** [comment]
> > Hi, i also want to know how can i get the free surface elevation and pressure data because the out file seems dont include the free surface.
> 
> Free surface elevation and the hydrodynamic pressure are equivalent in nondimensional value at the free surface.

Hi, How can i see the elevation data?  Which file is the result in the output? It seems can not see it in the BEMrosetta

**Comment by YingyiLiu** [comment]
You can find the data in the *.6p file.

**Comment by Dylan0824** [comment]
> You can find the data in the *.6p file.
 
Thank you so much for your reply!

**Comment by Dylan0824** [comment]
Dear professor, sorry to bother you again,
i create a file that calculate the elevation and when i calculate this in 3 different frequency, the result is this
![1681216413500](https://user-images.githubusercontent.com/115965311/231163621-8a21e9f8-9ce8-4ef5-9bc4-ff2ee36731b9.png)
but, when i just calculate one frequency, it turns that
![1681216485324](https://user-images.githubusercontent.com/115965311/231163772-e441a43d-c6bb-4a65-b67b-c3ca62b1216c.png)
I dont know whats the meanting of this
![1681216544053](https://user-images.githubusercontent.com/115965311/231164005-b0559e15-dbfc-4221-92b1-48135030dd75.png)
![1681216555467](https://user-images.githubusercontent.com/115965311/231164052-969a1c35-ce6b-4662-869c-168c91391574.png)
while it doesnt exeist in the result with one frequency.

Sorry to bother you again and thank you vert much!

**Comment by Dylan0824** [comment]
Hi,
when i run the program, it will produce a file called ErrorCheck.txt in the output file, but why the rotation center is different from what i set in the control file .
For example, i set the 'Reference_body_center       -0.356       0.000       0.000' in the control file, and in the hydrostatic.in, the rotation center is  -0.356       0.000       0.000 too, but in the ErrorCheck.txt, it turns out 
'The rotation center is input as (please confirm if it is correct):
       0.000       0.356       0.000'

**Comment by YingyiLiu** [comment]
> Dear professor, sorry to bother you again, i create a file that calculate the elevation and when i calculate this in 3 different frequency, the result is this ![1681216413500](https://user-images.githubusercontent.com/115965311/231163621-8a21e9f8-9ce8-4ef5-9bc4-ff2ee36731b9.png) but, when i just calculate one frequency, it turns that ![1681216485324](https://user-images.githubusercontent.com/115965311/231163772-e441a43d-c6bb-4a65-b67b-c3ca62b1216c.png) I dont know whats the meanting of this ![1681216544053](https://user-images.githubusercontent.com/115965311/231164005-b0559e15-dbfc-4221-92b1-48135030dd75.png) ![1681216555467](https://user-images.githubusercontent.com/115965311/231164052-969a1c35-ce6b-4662-869c-168c91391574.png) while it doesnt exeist in the result with one frequency.
> 
> Sorry to bother you again and thank you vert much!

Regarding the Wamit-format output, please refer to the user manual of Wamit: https://www.wamit.com/manual.htm

**Comment by YingyiLiu** [comment]
> 



> Hi, when i run the program, it will produce a file called ErrorCheck.txt in the output file, but why the rotation center is different from what i set in the control file . For example, i set the 'Reference_body_center -0.356 0.000 0.000' in the control file, and in the hydrostatic.in, the rotation center is -0.356 0.000 0.000 too, but in the ErrorCheck.txt, it turns out 'The rotation center is input as (please confirm if it is correct): 0.000 0.356 0.000'

Thanks. The problem has been corrected.
