### ISSUE TITLE
fort.4 file

### ISSUE THREAD

**Issue by ucar398** [YingyiLiu/HAMS#3]
Hi Mr. Liu

I have a problem with the mesh converter. The rest of the documents are okay, but the converter is not generating the "fort.4" file even if I use your files "marin_semi_low.gdf" and "HywindSpar_Half.gdf". I have deleted and recloned, nothing changed.

I really appreciate any help you can provide.

**Comment by YingyiLiu** [comment]
Thank you for providing this feedback. I will fix the issue as early as
possible.

ucar398 <notifications@github.com> 于2021年2月22日周一 下午9:15写道：

**Comment by YingyiLiu** [comment]
@ucar398 The built-in mesh converter WAMIT_MeshTran is now updated and can generate directly the Hydrostatic.in file. Please refer to the user manual for details.

**Comment by ucar398** [comment]
@YingyiLiu Thank you for your interest.
