### ISSUE TITLE
Numerical integration over panels

### ISSUE THREAD

**Issue by mancellin** [YingyiLiu/HAMS#32]
Dear @YingyiLiu,

I'm looking for a small bit of information that I could not find in the papers describing HAMS.
About the integration of the Green function over a panel: the singular part is integrated with analytical formulas as presented in [Liu, JMSE, 2019], but what about the rest (wave part of the Green function)?
I could not find any reference to quadrature scheme in the code, so I'm assuming the integration is done by evaluating the Green function at a single point at the center of the cell. Is that right?

**Comment by YingyiLiu** [comment]
Dear Matthieu,

Yes, exactly, you are correct. This is because the single-point rule seems to be sufficient for linear forces.

**Comment by mancellin** [comment]
Thank you for the clarification!
