### ISSUE TITLE
Fortran runtime error: Assignment of scalar to unallocated array

### ISSUE THREAD

**Issue by ramisetti** [YingyiLiu/HAMS#6]
I get the following runtime error while trying to run the HAMS Solver. Can you please help me to fix this?

 -----------------------------------------------------------------------------------------------

At line 60 of file HydroStatic.f90
Fortran runtime error: Assignment of scalar to unallocated array

Error termination. Backtrace:
#0  0x42f9ac in __hydrostatic_MOD_initialisation
	at /soft/opensoft/HAMS/11May2021/SourceCode/HydroStatic.f90:60
#1  0x43f8ec in __hams_lib_MOD_exec
	at /soft/opensoft/HAMS/11May2021/SourceCode/HAMS_Prog.f90:125
#2  0x40179e in hams
	at /soft/opensoft/HAMS/11May2021/SourceCode/HAMS_Prog.f90:392
#3  0x40179e in main
	at /soft/opensoft/HAMS/11May2021/SourceCode/HAMS_Prog.f90:391

**Comment by gbarter** [comment]
This should be resolved in the PR

**Comment by ramisetti** [comment]
thank you. I will check

**Comment by YingyiLiu** [comment]
Garrett, thanks for your effort. I checked all your 6 commits and found no problem. I've merged them to the master repository.

**Comment by YingyiLiu** [comment]
Srinivasa, thanks for the reporting issues. Just a reminder, Issue #4  and Issue #6 have been resolved by Garret and have been now reflected in the main repository.
