### ISSUE TITLE
Continuous Integration needed

### ISSUE THREAD

**Issue by gbarter** [YingyiLiu/HAMS#7]
Many of the compatibility issues with `gfortran` could be addressed with a Continuous Integration suite of tests that get executed on every commit with GitHub actions.  I am envisioning a test matrix across windows, mac, and linux and a couple gfortran versions.  Tests would include compiling and running the suite of tests already present in the repository.  I would be happy to help with this.

Cheers,
Garrett

**Comment by ramisetti** [comment]
I agree with @gbarter. Including a continuous integration suits of tests will be really helpful.

**Comment by YingyiLiu** [comment]
Thanks, Garret, that's a great idea. But to be honest, my knowledge of gfortran is quite limited although I did have some experience of using it before. The tests as you proposed are certainly very helpful to the users (particularly those not using the Intel Fortran).  I therefore strongly encourage you to carry out these tests and summarize the results in a report or publication as freely as you like. And I will be very glad to offer my help if you need. By the way, your great efforts in doing all of these and making the Linux version of HAMS are very much appreciated by all of us.
